CREATE TABLE `items` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`product_id` INT(255) NULL DEFAULT NULL,
	`details` VARCHAR(1000) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6;
