CREATE TABLE `product` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`item_name` VARCHAR(255) NULL DEFAULT NULL,
	`item_image` VARCHAR(255) NULL DEFAULT NULL,
	`item_desc` VARCHAR(1000) NULL DEFAULT NULL,
	`price` VARCHAR(250) NULL DEFAULT NULL,
	`stock` INT(255) NULL DEFAULT NULL,
	`sold` INT(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=13;
